#!/system/bin/sh

(su -c 'flag=0
busybox script -q -c "getevent /dev/input/event0" /dev/null </dev/null | while read code1 code2 code3
do
led_screen=$(cat /sys/class/leds/lcd_backlight0/brightness)
led_torch=$(cat /sys/class/leds/torch/brightness)
if [[ "$led_screen" -eq "0" ]]
then
if [[ "$code2" -eq "0072" && "$code3" -eq "00000001" ]]
then
flag=1
elif [[ "$code2" -eq "0073" && "$code3" -eq "00000001" && "$flag" -eq "1" ]]
then
led_torch=$(expr 8 - $led_torch)
echo "$led_torch" > /sys/class/leds/torch/brightness
elif [[ "$code2" -eq "0072" && "$code3" -eq "00000000" ]]
then
flag=0
fi
fi
done') &